import type { Store } from './types';
const date = '2026-10-02T12:00:00.000Z';
const people = [
  ['Sophie K.', '+32476123456'],
  ['Marc B.', '+32487123456'],
  ['Laura V.', '+32498123456'],
  ['Anke D.', '+32475123456'],
  ['Thomas M.', '+32468123456'],
  ['Emma S.', '+32479123456'],
  ['Pieter L.', '+32492123456'],
];
export const initialStore: Store = {
  business: {
    id: 'de-vos',
    name: 'Bakkerij De Vos',
    logoUrl: '',
    accentColor: '#315F9A',
    googleReviewUrl: '',
    phone: '+32 16 23 45 67',
    email: 'hallo@bakkerijdevos.be',
    defaultSms:
      'Dag {naam}, bedankt voor je bezoek aan {bedrijf}!\nHoe was je ervaring?\nBeoordeel ons via:\n{link}',
    notifyFeedback: true,
  },
  customers: people.map(([name, phone], i) => ({
    id: `c${i}`,
    businessId: 'de-vos',
    name,
    phone,
    createdAt: date,
  })),
  invitations: people.map((_, i) => ({
    id: `i${i}`,
    customerId: `c${i}`,
    businessId: 'de-vos',
    token: i === 0 ? '7x9q' : `demo${i}`,
    status: 'completed',
    sentAt: date,
    message: 'Bedankt voor je bezoek! Hoe was je ervaring?',
  })),
  ratings: [5, 2, 5, 3, 4, 5, 2].map((stars, i) => ({
    id: `rating${i}`,
    invitationId: `i${i}`,
    stars,
    createdAt: date,
  })),
  reviews: [
    {
      id: 'rev0',
      customerId: 'c0',
      businessId: 'de-vos',
      stars: 5,
      text: 'Altijd vriendelijk ontvangen en de lekkerste koffiekoeken van de buurt. Een vaste stop op zaterdagochtend!',
      platform: 'Google',
      createdAt: date,
    },
    {
      id: 'rev2',
      customerId: 'c2',
      businessId: 'de-vos',
      stars: 5,
      text: 'Heerlijk vers brood en supervriendelijke bediening. Je proeft dat alles met zorg wordt gemaakt.',
      platform: 'Google',
      createdAt: date,
    },
    {
      id: 'rev4',
      customerId: 'c4',
      businessId: 'de-vos',
      stars: 4,
      text: 'Fijne bakkerij met een mooi aanbod. De zuurdesembroden zijn een aanrader.',
      platform: 'Google',
      createdAt: '2026-09-30T10:00:00Z',
    },
    {
      id: 'rev5',
      customerId: 'c5',
      businessId: 'de-vos',
      stars: 5,
      text: 'Onze verjaardagstaart was prachtig én lekker. Bedankt voor de goede service!',
      platform: 'Google',
      createdAt: '2026-09-29T10:00:00Z',
    },
  ],
  feedback: [
    {
      id: 'f1',
      ratingId: 'rating1',
      message: 'Lange wachttijd aan de kassa vanochtend.',
      contactAllowed: true,
      status: 'open',
      createdAt: date,
    },
    {
      id: 'f2',
      ratingId: 'rating3',
      message: 'Bestelling klopte niet helemaal.',
      contactAllowed: false,
      status: 'resolved',
      createdAt: '2026-09-29T10:00:00Z',
    },
    {
      id: 'f3',
      ratingId: 'rating6',
      message: 'Het brood was al uitverkocht toen ik langskwam. Misschien iets meer voorzien?',
      contactAllowed: true,
      status: 'open',
      createdAt: '2026-10-01T10:00:00Z',
    },
  ],
};
